name: Java CI with Maven

on:
  # Trigger the workflow on push or pull request events to the main branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    # Specify the environment to run the job
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - uses: actions/checkout@v4

    # Step 2: Set up JDK 17 environment
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'        # Specify the Java version to use
        distribution: 'temurin'  # Use the Eclipse Temurin distribution of JDK
        cache: maven             # Enable caching of Maven dependencies

    # Step 3: Run tests for the specified class using Maven
    - name: Build and test with Maven
      run: mvn test -Dtest=com.springboot.CartOfferApplicationTests

    # Step 4: Clean up after the build and tests
    - name: Clean up after run
      run: mvn clean
